export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
export const SET_CURRENT_LIST = "SET_CURRENT_LIST";
export const ADD_NEW_EVENT = "ADD_NEW_EVENT";
export const FETCH_FROM_LOCAL = "FETCH_FROM_LOCAL";
export const SHOW_ADD_NEW_EVENT = "SHOW_ADD_NEW_EVENT";
export const CLOSE_ADD_NEW_EVENT = "CLOSE_ADD_NEW_EVENT";
